// <auto-generated />
using System;
using KomPas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KomPas.Migrations
{
    [DbContext(typeof(KomPasContext))]
    [Migration("20210529201442_PrvaMigracija")]
    partial class PrvaMigracija
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("KomPas.Models.Dokument", b =>
                {
                    b.Property<int>("DokumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Datoteka")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DokumentID");

                    b.ToTable("Dokument");
                });

            modelBuilder.Entity("KomPas.Models.Forum", b =>
                {
                    b.Property<int>("ForumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BrojAktivnihKorisnika")
                        .HasColumnType("int");

                    b.HasKey("ForumID");

                    b.ToTable("Forum");
                });

            modelBuilder.Entity("KomPas.Models.Komentar", b =>
                {
                    b.Property<int>("KomentarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AutorKomentaraID")
                        .HasColumnType("int");

                    b.Property<int>("DokumentID")
                        .HasColumnType("int");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("VrijemeObjave")
                        .HasColumnType("datetime");

                    b.HasKey("KomentarID");

                    b.HasIndex("AutorKomentaraID");

                    b.HasIndex("DokumentID");

                    b.ToTable("Komentar");
                });

            modelBuilder.Entity("KomPas.Models.Korisnik", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PasID")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("PasID");

                    b.ToTable("Korisnik");
                });

            modelBuilder.Entity("KomPas.Models.Pas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("KastriranSterilisan")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Rasa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slika")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Spol")
                        .HasColumnType("int");

                    b.Property<int>("Tezina")
                        .HasColumnType("int");

                    b.Property<string>("ZdravstveniProblem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Pas");
                });

            modelBuilder.Entity("KomPas.Models.Podsjetnik", b =>
                {
                    b.Property<int>("PodsjetnikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Termin")
                        .HasColumnType("datetime");

                    b.HasKey("PodsjetnikID");

                    b.ToTable("Podsjetnik");
                });

            modelBuilder.Entity("KomPas.Models.Post", b =>
                {
                    b.Property<int>("PostID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AutorPostaID")
                        .HasColumnType("int");

                    b.Property<int>("BrojKomentara")
                        .HasColumnType("int");

                    b.Property<int>("BrojReakcija")
                        .HasColumnType("int");

                    b.Property<int>("DokumentID")
                        .HasColumnType("int");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PostID");

                    b.HasIndex("AutorPostaID");

                    b.HasIndex("DokumentID");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("KomPas.Models.Profil", b =>
                {
                    b.Property<int>("ProfilID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("KorisnikID")
                        .HasColumnType("int");

                    b.Property<int>("PasID")
                        .HasColumnType("int");

                    b.HasKey("ProfilID");

                    b.HasIndex("KorisnikID");

                    b.HasIndex("PasID");

                    b.ToTable("Profil");
                });

            modelBuilder.Entity("KomPas.Models.ZahtjevZaUdomljavanje", b =>
                {
                    b.Property<int>("ZahtjevZaUdomljavanjeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ImaPsa")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IzabraniPasID")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikID")
                        .HasColumnType("int");

                    b.HasKey("ZahtjevZaUdomljavanjeID");

                    b.HasIndex("IzabraniPasID");

                    b.HasIndex("KorisnikID");

                    b.ToTable("ZahtjevZaUdomljavanje");
                });

            modelBuilder.Entity("KomPas.Models.Komentar", b =>
                {
                    b.HasOne("KomPas.Models.Korisnik", "AutorKomentara")
                        .WithMany()
                        .HasForeignKey("AutorKomentaraID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KomPas.Models.Dokument", "Dokument")
                        .WithMany()
                        .HasForeignKey("DokumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KomPas.Models.Korisnik", b =>
                {
                    b.HasOne("KomPas.Models.Pas", "Pas")
                        .WithMany()
                        .HasForeignKey("PasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KomPas.Models.Post", b =>
                {
                    b.HasOne("KomPas.Models.Korisnik", "AutorPosta")
                        .WithMany()
                        .HasForeignKey("AutorPostaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KomPas.Models.Dokument", "Dokument")
                        .WithMany()
                        .HasForeignKey("DokumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KomPas.Models.Profil", b =>
                {
                    b.HasOne("KomPas.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KomPas.Models.Pas", "Pas")
                        .WithMany()
                        .HasForeignKey("PasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KomPas.Models.ZahtjevZaUdomljavanje", b =>
                {
                    b.HasOne("KomPas.Models.Pas", "IzabraniPas")
                        .WithMany()
                        .HasForeignKey("IzabraniPasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KomPas.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
